version: '3.4'

services:
    ts:
        image: Pal-comp:5000/tomcat:8
        labels:
            name: ts
            version: 1.0
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - "node.labels.type == dev"
        ports:
            - "8080:8080"
